apiVersion: v1
kind: ConfigMap
metadata:
  name: smartdesk-config
  namespace: smartdesk-canary
data:
  POSTGRES_HOST: "postgres.smartdesk-canary.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "smartdesk"
  POSTGRES_DB: "smartdesk"
  REDIS_HOST: "redis.smartdesk-canary.svc.cluster.local"
  REDIS_PORT: "6379"
  NATS_URL: "nats://nats.smartdesk-canary.svc.cluster.local:4222"
  MINIO_ENDPOINT: "minio.smartdesk-canary.svc.cluster.local:9000"
