#!/usr/bin/env python3
"""Generate Alpha-local secrets for smart-desk deploy/docker-compose.alpha.yml.

Creates deploy/alpha/.env with:
- SERVICE_JWT_PRIVATE_KEY / SERVICE_JWT_PUBLIC_KEY (gateway signs service-jwt)
- CORE_SERVICE_JWT_PUBLIC_KEY (core verifies insight/gateway tokens, aud=core)
- CORE_SERVICE_TOKEN (insight -> core internal user directory, aud=core)
- JWT_SECRET (gateway user-session signing)

Alignment with smartdesk-gateway ServiceJwtService (RS256, iss=smartdesk-gateway):
- Gateway inbound to insight: aud=insight, signed per-request at runtime
- Insight outbound to core: static CORE_SERVICE_TOKEN with aud=core (service identity)

Requires: pip install pyjwt cryptography
"""
from __future__ import annotations

import argparse
import base64
import secrets
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

try:
    import jwt
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa
except ImportError as exc:
    print(
        "Missing dependency. Run: pip install pyjwt cryptography",
        file=sys.stderr,
    )
    raise SystemExit(1) from exc

# Stable Alpha service identity for insight -> core directory lookups.
INSIGHT_CORE_SERVICE_SUB = "00000000-0000-4000-8000-000000000001"
SERVICE_JWT_ISSUER = "smartdesk-gateway"
CORE_SERVICE_JWT_AUDIENCE = "core"
INSIGHT_SERVICE_JWT_AUDIENCE = "insight"
# Alpha static token TTL: 365 days (rotate via re-running this script).
CORE_SERVICE_TOKEN_TTL_SECONDS = 365 * 24 * 3600


def _pem_to_env_value(pem: str) -> str:
    return '"' + pem.replace("\n", "\\n") + '"'


def _generate_rsa_keypair() -> tuple[str, str]:
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()
    public_pem = (
        private_key.public_key()
        .public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        )
        .decode()
    )
    return private_pem, public_pem


def _mint_core_service_token(private_pem: str) -> str:
    now = datetime.now(timezone.utc)
    payload = {
        "sub": INSIGHT_CORE_SERVICE_SUB,
        "roles": ["admin"],
        "org_id": "default",
        "iss": SERVICE_JWT_ISSUER,
        "aud": CORE_SERVICE_JWT_AUDIENCE,
        "iat": int(now.timestamp()),
        "nbf": int(now.timestamp()),
        "exp": int((now + timedelta(seconds=CORE_SERVICE_TOKEN_TTL_SECONDS)).timestamp()),
    }
    return jwt.encode(payload, private_pem, algorithm="RS256")


def _generate_jwt_secret() -> str:
    return base64.urlsafe_b64encode(secrets.token_bytes(32)).decode().rstrip("=")


def write_alpha_env(output: Path, *, force: bool) -> None:
    if output.exists() and not force:
        raise SystemExit(f"{output} already exists; pass --force to overwrite")

    private_pem, public_pem = _generate_rsa_keypair()
    core_service_token = _mint_core_service_token(private_pem)
    jwt_secret = _generate_jwt_secret()

    lines = [
        "# Generated by deploy/scripts/generate-alpha-secrets.py",
        "# Alpha-local only — do NOT reuse in production.",
        "",
        f"JWT_SECRET={jwt_secret}",
        "JWT_ISSUER=smartdesk-gateway",
        "JWT_AUDIENCE=smartdesk",
        "",
        "SERVICE_JWT_ALGORITHM=RS256",
        f"SERVICE_JWT_PRIVATE_KEY={_pem_to_env_value(private_pem)}",
        f"SERVICE_JWT_PUBLIC_KEY={_pem_to_env_value(public_pem)}",
        f"CORE_SERVICE_JWT_PUBLIC_KEY={_pem_to_env_value(public_pem)}",
        "CORE_SERVICE_JWT_AUDIENCE=core",
        "CORE_SERVICE_JWT_ISSUER=smartdesk-gateway",
        "",
        f"CORE_SERVICE_TOKEN={core_service_token}",
        "",
        "# Reference (gateway runtime signs per-user tokens with aud=insight)",
        f"# INSIGHT_SERVICE_JWT_AUDIENCE={INSIGHT_SERVICE_JWT_AUDIENCE}",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")

    example = output.parent / ".env.example"
    if not example.exists():
        example.write_text(
            "\n".join(
                [
                    "# Copy to .env: python deploy/scripts/generate-alpha-secrets.py",
                    "JWT_SECRET=<run script>",
                    "SERVICE_JWT_PRIVATE_KEY=<run script>",
                    "SERVICE_JWT_PUBLIC_KEY=<run script>",
                    "CORE_SERVICE_JWT_PUBLIC_KEY=<run script>",
                    "CORE_SERVICE_TOKEN=<run script>",
                ]
            )
            + "\n",
            encoding="utf-8",
        )

    print(f"Wrote {output}")
    print("Next:")
    print("  docker compose -f deploy/docker-compose.alpha.yml --env-file deploy/alpha/.env up -d --build")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "alpha" / ".env",
        help="Output .env path (default: deploy/alpha/.env)",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite existing file")
    args = parser.parse_args()
    write_alpha_env(args.output, force=args.force)


if __name__ == "__main__":
    main()
