/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登录（US-1.1）
         * @description 有效凭证→签发 JWT(access+refresh)；无效→401 且不下发令牌，错误提示不泄露账号是否存在。 **OQ-W2 安全裁决（2026-06-15）**：refresh_token 通过 `Set-Cookie: sd_rt=<token>; HttpOnly; Secure; SameSite=Strict; Path=/api/v1/auth` 下发，不在 JSON 响应体中返回。 前端 JS 不可读取该 Cookie；刷新请求由浏览器自动携带。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description `sd_rt=<refresh_token>; HttpOnly; Secure; SameSite=Strict; Path=/api/v1/auth; Max-Age=604800` （7天，仅 /api/v1/auth 路径可用，JS 不可读） */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                /** @description 凭证无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新令牌（US-1.1 AC3）
         * @description **OQ-W2 安全裁决（2026-06-15）**：浏览器自动携带 `sd_rt` HttpOnly Cookie， 无需（且不接受）在请求体中传递 refresh_token。 刷新成功后轮换 refresh_token（旧 Cookie 失效），并通过 `Set-Cookie` 下发新 Cookie。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        /** @description 轮换后的新 refresh_token Cookie（属性同登录） */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                /** @description 刷新令牌无效/过期，需重新登录 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登出（会话失效，后续请求 401，US-1.1 AC4）
         * @description 服务端吊销 refresh_token（Redis 删除），并通过 Set-Cookie 将 sd_rt Cookie 清除（Max-Age=0）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        /** @description `sd_rt=; HttpOnly; Secure; SameSite=Strict; Path=/api/v1/auth; Max-Age=0`（清除 Cookie） */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户与角色 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工单列表（按角色范围收敛：requester 仅自己；agent/lead 本组；manager 只读全局） */
        get: {
            parameters: {
                query?: {
                    status?: string;
                    priority?: string;
                    assignee_id?: string;
                    category_id?: string;
                    q?: string;
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketPage"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** 提单（requester+；US-2.1）。转发 core 建单，AI 分析异步、不阻塞。 */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TicketCreate"];
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ticket"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** 工单详情（聚合 core 详情 + insight 相似/建议；越权 403） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TicketAggregate"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新工单（agent+；manager 改工单→403） */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TicketUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ticket"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        trace?: never;
    };
    "/tickets/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 状态流转（转发 core；非法跃迁 409；幂等） */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransitionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ticket"];
                    };
                };
                403: components["responses"]["Forbidden"];
                /** @description 非法跃迁 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 分派/改派/转派/升级（lead+；US-2.3/US-5.1） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignmentRequest"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** 评论列表（requester 不返回 internal 备注，US-2.4 AC2） */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommentPage"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** 新增评论/内部备注（含 @提及；internal 仅 agent/lead/manager） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommentCreate"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** 附件列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttachmentView"][];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** 申请上传（≤20MB+白名单，OQ-9） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AttachmentInit"];
                };
            };
            responses: {
                /** @description 预签名上传 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AttachmentUpload"];
                    };
                };
                /** @description 超限 */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 类型不在白名单 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{attId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attId: string;
            };
            cookie?: never;
        };
        /** 下载附件（鉴权；越权 403，US-2.7 AC2） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    attId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 重定向到短时签名 URL */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}/sla": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** SLA 查询（US-2.5） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SlaView"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** 时间线/审计（US-2.8） */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimelinePage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}/csat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** 查询满意度评价（D5 一期对外；读取来源=core 工单详情 csat_score/csat_comment/csat_rated_at，映射 CsatView，不另开 core GET 端点） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CsatView"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** 解决后满意度评价 1-5 星（OQ-12/US-6.3；映射 core POST /tickets/{id}/csat） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CsatCreate"];
                };
            };
            responses: {
                /** @description 已评价 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                /** @description 非可评价状态 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** 相似工单推荐（懒加载，不阻塞详情；US-3.3） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimilarList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}/suggestion": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** 分类/定级建议（一期建议态；坐席可采纳/修改，US-3.1/US-3.2） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuggestionView"];
                    };
                };
            };
        };
        put?: never;
        /** 采纳/纠偏分类（写回 core + 回流 insight feedback，US-3.1 AC3） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TicketId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SuggestionDecision"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ticket"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 看板聚合（manager/lead 只读；US-6.2/US-6.3） */
        get: {
            parameters: {
                query: {
                    metric: components["schemas"]["StatsMetric"];
                    group_by?: "time" | "category" | "assignee" | "priority" | "status";
                    interval?: "hour" | "day" | "week" | "month";
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatsResult"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出 CSV（US-6.4） */
        get: {
            parameters: {
                query: {
                    metric: components["schemas"]["StatsMetric"];
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 站内通知列表（US-4.2） */
        get: {
            parameters: {
                query?: {
                    unread_only?: boolean;
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notifId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notifId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 标记已读 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    notifId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分类树（转发 core） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"][];
                    };
                };
            };
        };
        put?: never;
        /** 新增分类（admin） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryCreate"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/sla-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SLA 策略 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SlaPolicy"][];
                    };
                };
            };
        };
        /** 配置 SLA 策略（admin） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SlaPolicy"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SlaPolicy"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户/角色（admin） */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserPage"];
                    };
                };
            };
        };
        put?: never;
        /** 创建用户并授角色（admin） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserCreate"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/notification-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 通知策略 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationPolicy"][];
                    };
                };
            };
        };
        /** 配置通知策略（admin，US-4.4） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NotificationPolicy"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: Record<string, never>[];
            trace_id?: string;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        /** @description 仅含 access_token；refresh_token 通过 HttpOnly Cookie（sd_rt）下发，不在响应体中出现（OQ-W2）。 */
        TokenPair: {
            access_token?: string;
            /** @default Bearer */
            token_type: string;
            /** @description access 有效秒数 */
            expires_in?: number;
        };
        /** @description 当前用户视图（D4：对外契约不暴露 org_id，租户由 gateway 从 JWT 注入下游） */
        Me: {
            /** Format: uuid */
            user_id?: string;
            username?: string;
            display_name?: string;
            roles?: ("requester" | "agent" | "lead" | "manager" | "admin")[];
        };
        TicketCreate: {
            title: string;
            description: string;
            /** Format: uuid */
            category_id?: string | null;
            /** @enum {string} */
            priority?: "P1" | "P2" | "P3" | "P4";
            attachment_ids?: string[];
        };
        TicketUpdate: {
            title?: string;
            description?: string;
            /** Format: uuid */
            category_id?: string;
            /** @enum {string} */
            priority?: "P1" | "P2" | "P3" | "P4";
        };
        Ticket: {
            /** Format: uuid */
            id?: string;
            /** @example SD-2026-000123 */
            number?: string;
            title?: string;
            /** @enum {string} */
            status?: "new" | "accepted" | "in_progress" | "pending_user" | "resolved" | "closed" | "suspended" | "cancelled";
            /** @enum {string} */
            priority?: "P1" | "P2" | "P3" | "P4";
            /** Format: uuid */
            assignee_id?: string | null;
            /** Format: uuid */
            category_id?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        TicketAggregate: components["schemas"]["Ticket"] & {
            description?: string;
            sla?: Record<string, never>;
            /** @description insight 分类/定级建议 */
            suggestion?: Record<string, never>;
            /** @description insight 相似工单（懒加载） */
            similar?: Record<string, never>[];
            comments_count?: number;
        };
        TicketPage: {
            items?: components["schemas"]["Ticket"][];
            page?: number;
            page_size?: number;
            total?: number;
        };
        TransitionRequest: {
            /** @enum {string} */
            action: "accept" | "start" | "wait_user" | "resolve" | "close" | "reopen" | "suspend" | "resume" | "cancel";
            reason?: string;
        };
        AssignmentRequest: {
            /** @enum {string} */
            kind: "manual" | "auto" | "reassign" | "escalate";
            /** Format: uuid */
            to_user_id?: string | null;
            /** Format: uuid */
            to_group_id?: string | null;
            reason?: string;
        };
        CommentCreate: {
            body: string;
            /** @enum {string} */
            visibility: "public" | "internal";
            mentions?: string[];
        };
        CommentPage: {
            items?: {
                /** Format: uuid */
                id?: string;
                body?: string;
                /** @enum {string} */
                visibility?: "public" | "internal";
                /** Format: uuid */
                author_id?: string;
                /** Format: date-time */
                created_at?: string;
            }[];
            page?: number;
            page_size?: number;
            total?: number;
        };
        AttachmentInit: {
            filename: string;
            content_type: string;
            size_bytes: number;
            /**
             * Format: uuid
             * @description 可选，挂到指定评论；透传 core AttachmentInit.comment_id
             */
            comment_id?: string | null;
        };
        SuggestionDecision: {
            accepted: boolean;
            /**
             * Format: uuid
             * @description 采纳/纠偏后的分类
             */
            category_id?: string | null;
            /** @enum {string|null} */
            priority?: "P1" | "P2" | "P3" | "P4" | null;
        };
        CsatCreate: {
            score: number;
            comment?: string;
        };
        /** @description 满意度只读视图（GET /tickets/{id}/csat）。由 core 工单详情附加字段映射，不另开 core GET： score←csat_score、comment←csat_comment、rated_at←csat_rated_at（后两者为 core 1.0.x 附加字段）。 */
        CsatView: {
            /** @description 映射 core Ticket.csat_score */
            score?: number | null;
            /** @description 映射 core Ticket.csat_comment */
            comment?: string | null;
            /**
             * Format: date-time
             * @description 映射 core Ticket.csat_rated_at
             */
            rated_at?: string | null;
        };
        AttachmentView: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ticket_id?: string;
            /**
             * Format: uuid
             * @description 所属评论（若有）；透传 core Attachment.comment_id
             */
            comment_id?: string | null;
            filename?: string;
            content_type?: string;
            size_bytes?: number;
            /** Format: uuid */
            uploader_id?: string;
            /** Format: date-time */
            created_at?: string;
        };
        AttachmentUpload: {
            /** Format: uuid */
            attachment_id?: string;
            /**
             * Format: uri
             * @description 预签名上传 URL（短时）
             */
            url?: string;
            /** @example PUT */
            method?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        SlaView: {
            /** @enum {string} */
            priority?: "P1" | "P2" | "P3" | "P4";
            /** Format: date-time */
            response_due_at?: string;
            /** Format: date-time */
            resolve_due_at?: string;
            response_met?: boolean;
            resolve_met?: boolean;
            paused?: boolean;
            breached?: boolean;
        };
        SuggestionView: {
            /** Format: uuid */
            category_id?: string | null;
            /** Format: float */
            confidence?: number;
            /** @enum {string} */
            priority?: "P1" | "P2" | "P3" | "P4";
            /** @description 是否已自动填充（一期默认建议态，OQ-4） */
            applied?: boolean;
        };
        SimilarList: {
            items?: {
                /** Format: uuid */
                ticket_id?: string;
                number?: string;
                title?: string;
                /**
                 * Format: float
                 * @description 相似度 0-1，语义实现中立（OQ-5）
                 */
                score?: number;
                summary?: string;
            }[];
        };
        TimelineEntry: {
            /** Format: uuid */
            id?: string;
            event_type?: string;
            /** Format: uuid */
            actor_id?: string | null;
            payload?: Record<string, never>;
            /** Format: date-time */
            created_at?: string;
        };
        TimelinePage: {
            items?: components["schemas"]["TimelineEntry"][];
            page?: number;
            page_size?: number;
            total?: number;
        };
        /**
         * @description 与 insight.yaml /stats/aggregate 的 metric 同一枚举
         * @enum {string}
         */
        StatsMetric: "volume" | "sla_attainment" | "resolution_time" | "backlog" | "reopen_rate" | "agent_workload" | "csat";
        StatsResult: {
            metric?: components["schemas"]["StatsMetric"];
            group_by?: string;
            interval?: string;
            series?: {
                key?: string;
                value?: number;
            }[];
            /** Format: date-time */
            generated_at?: string;
        };
        NotificationItem: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            ticket_id?: string | null;
            type?: string;
            title?: string;
            body?: string;
            /** Format: date-time */
            read_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        NotificationPage: {
            items?: components["schemas"]["NotificationItem"][];
            page?: number;
            page_size?: number;
            total?: number;
            unread_count?: number;
        };
        NotificationPolicy: {
            /** @enum {string} */
            role: "requester" | "agent" | "lead" | "manager" | "admin";
            event_type: string;
            /** @enum {string} */
            channel: "inapp" | "email";
            enabled: boolean;
        };
        Category: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            parent_id?: string | null;
            code?: string;
            name?: string;
            active?: boolean;
            sort?: number;
        };
        CategoryCreate: {
            /** Format: uuid */
            parent_id?: string | null;
            code?: string;
            name: string;
            sort?: number;
        };
        SlaPolicy: {
            /** Format: uuid */
            id?: string;
            name: string;
            active?: boolean;
            targets: {
                /** @enum {string} */
                priority?: "P1" | "P2" | "P3" | "P4";
                response_minutes?: number;
                resolve_minutes?: number;
            }[];
        };
        User: {
            /** Format: uuid */
            id?: string;
            username?: string;
            /** Format: email */
            email?: string;
            display_name?: string;
            /** @enum {string} */
            status?: "active" | "disabled";
            roles?: ("requester" | "agent" | "lead" | "manager" | "admin")[];
        };
        UserCreate: {
            username: string;
            /** Format: email */
            email?: string;
            display_name: string;
            roles: ("requester" | "agent" | "lead" | "manager" | "admin")[];
        };
        UserPage: {
            items?: components["schemas"]["User"][];
            page?: number;
            page_size?: number;
            total?: number;
        };
    };
    responses: {
        /** @description 校验失败 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未认证/令牌过期 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 越权（RBAC 拒绝，记审计） */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 超出速率阈值（US-1.3 AC2） */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        TicketId: string;
        IdempotencyKey: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
