apiVersion: v1
kind: Service
metadata:
  name: gateway-stable
  namespace: smartdesk-canary
spec:
  selector:
    app: gateway
    version: stable
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-canary
  namespace: smartdesk-canary
spec:
  selector:
    app: gateway
    version: canary
  ports:
    - port: 80
      targetPort: 3000
